name: Test send slack message
on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Message
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Deployment result of repository: ${{ github.event.repository.name }}\n Status: ${{ job.status }}\n Platform: iOS\n Environment: Dev\n Link: https://deploygate.com/distributions/69eef9f83da35de6ee37a3045ea1ebe5a76fdff2"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
